CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	username VARCHAR(20) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS users_username
ON users(username);

CREATE TABLE IF NOT EXISTS friends (
	"user" BIGINT,
	friend BIGINT,
	PRIMARY KEY("user", friend),
	FOREIGN KEY("user") REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY(friend) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendrequests (
	id BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
	receiver BIGINT,
	sender BIGINT,
	FOREIGN KEY(receiver) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY(sender) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS friendrequests_receiver
ON friendrequests(receiver);

CREATE TABLE IF NOT EXISTS films (
	id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	owner BIGINT,
	Title VARCHAR(255) NOT NULL,
	Published INTEGER,
	Genres VARCHAR(255),
	"Length(min)" INTEGER,
	Director VARCHAR(255),
	Writer VARCHAR(255),
	Star VARCHAR(255),
	"Watched(owner)" BOOLEAN DEFAULT '0',
	Shared BOOLEAN DEFAULT '0',
	FOREIGN KEY(owner) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS films_owner
ON films(owner);

CREATE TABLE IF NOT EXISTS music (
	id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	owner BIGINT,
	Title VARCHAR(255) NOT NULL,
	Published INTEGER,
	Genres VARCHAR(255),
	Inteprator VARCHAR(255),
	Composer VARCHAR(255),
	Lyricist VARCHAR(255),
	Shared BOOLEAN DEFAULT '0',
	FOREIGN KEY(owner) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS music_owner
ON music(owner);

CREATE TABLE IF NOT EXISTS books (
	id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	owner BIGINT,
	Title VARCHAR(255) NOT NULL,
	Published INTEGER,
	Genres VARCHAR(255),
	Pages INTEGER,
	Author VARCHAR(255),
	"Read(owner)" BOOLEAN DEFAULT '0',
	Shared BOOLEAN DEFAULT '0',
	FOREIGN KEY(owner) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS books_owner
ON books(owner);

CREATE TABLE IF NOT EXISTS comics (
	id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	owner BIGINT,
	Title VARCHAR(255) NOT NULL,
	Published INT,
	Genres VARCHAR(255),
	Pages INT,
	Author VARCHAR(255),
	Illustrator VARCHAR(255),
	"Read(owner)" BOOLEAN DEFAULT '0',
	Shared BOOLEAN DEFAULT '0',
	FOREIGN KEY(owner) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS comics_owner
ON comics(owner);

CREATE TABLE IF NOT EXISTS games (
	id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	owner BIGINT,
	Title VARCHAR(255) NOT NULL,
	Published INT,
	Genres VARCHAR(255),
	Developer VARCHAR(255),
	Platform VARCHAR(255),
	Publisher VARCHAR(255),
	"Completed(owner)" BOOLEAN DEFAULT '0',
	Shared BOOLEAN DEFAULT '0',
	FOREIGN KEY(owner) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS games_owner
ON games(owner);

CREATE TABLE IF NOT EXISTS other (
	id SERIAL PRIMARY KEY NOT NULL UNIQUE,
	owner BIGINT,
	Title VARCHAR(255) NOT NULL,
	Published INT,
	Genres VARCHAR(255),
	Information VARCHAR(255),
	shared BOOLEAN DEFAULT '0',
	FOREIGN KEY(owner) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS other_owner
ON other(owner);
